### ISSUE TITLE
Add ELK to docker compose 

### ISSUE THREAD

**Issue by ashwinimanoj** [singsuyash/enterprise-platform#1]
Add ElasticSearch, Logstash and Kibana to docker compose.

**Comment by singsuyash** [comment]
Forked it from https://github.com/deviantony/docker-elk

**Comment by ashwinimanoj** [comment]
> Hi, testing something out
<sub>[View in Slack](https://vantage-loaf.slack.com/archives/C0141K7NAD6/p1589020705000800)</sub>
